version: "3.6"
services:
  proxy-ldap:
    image: 'dockermax83/squid-ldap:latest'
    container_name: 'proxy-ldap'
    ports:
      - "3128:3128"
    volumes:
      - ./squid/cache:/var/spool/squid
      - ./squid/conf:/etc/squid
      - ./squid/logs:/var/log/squid
    restart: unless-stopped
    environment:
      - TZ=America/Argentina/Buenos_Aires
