version: "3.6"
services:
  squid-ldap:
    image: 'dockermax83/squid-ldap:2020090301'
    #image: 'dockermax83/squid-ldap:latest'
    container_name: 'squid-ldap'
    ports:
      - "3128:3128"
    volumes:
      - ./squid/cache:/var/spool/squid
      - ./squid/conf:/etc/squid
      - ./squid/logs:/var/log/squid
    environment: 
      - LDAP_ENABLE=true
      - LDAP_HOST=10.2.8.2
      - LDAP_PORT=389
      - LDAP_DN="ou=Users,dc=dxi,dc=intranet"
      - LDAP_ATTRIBUT="uid=%s"
      - PROXY_NAME="Proxy DXI"
    restart: unless-stopped


